name: SuperServeurPlugin
main: com.samy.superserveur.SuperServeurPlugin
version: 1.0
api-version: 1.20
description: Mon premier plugin Minecraft Spigot.
author: Samy

commands:
  friends:
    description: Gère les amis
    usage: /friends help
  f:
    description: Gère les amis
    usage: /f help
  party:
    description: Gère les groupes
    usage: /party help
  p:
    description: Gère les groupes
    usage: /p help
  m:
    description: Envoyer un message privé
    usage: /m <pseudo> <message>
  r:
    description: Répondre au dernier message privé
    usage: /r <message>
  help:
    description: Affiche cette page
    usage: /help
